apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: team-a
  labels:
    energy: fossil
spec:
  owners:
  - name: alice
    kind: User
  namespaceOptions:
    quota: 1
  resourceQuotas:
    scope: Tenant
    items:
    - hard:
        limits.cpu: "8"
        limits.memory: 16Gi
        requests.cpu: "8"
        requests.memory: 16Gi
    - hard:
        pods: "10"
  limitRanges:
    items:
    - limits:
      - default:
          cpu: 500m
          memory: 512Mi
        defaultRequest:
          cpu: 100m
          memory: 10Mi
        type: Container